# Generated by Django 5.2 on 2025-05-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='pincode',
            new_name='zipcode',
        ),
    ]
